version: '2'
services:
  front:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    links:
      #- mysql:mysql
      #- redis:redis
      - mongo:mongo
      - memcached:memcached
      - lxHive:lxHive
    volumes:
      - ./www:/var/www
      - ./sites:/etc/nginx/conf.d
      - ./logs:/var/log/supervisor
      - ./certs:/etc/nginx/certs

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - mongoData

  mongoData:
    image: mongo
    entrypoint: /bin/bash

  memcached:
    image: memcached
    ports:
      - "11211:11211"

  lxHive:
    build: lxHive/.
    volumes_from:
      - nginx

  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"

  # mysql:
  #   image: mysql
  #   ports:
  #     - "3306:3306"
  #   volumes_from:
  #     - mysqlData
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password

  # mysqlData:
  #   image: mysql
  #   entrypoint: /bin/bash
